### PR TITLE
Update style.

### PR DESCRIPTION
**Pull request by stevemdixon**

### CODE REVIEW

**Comment by jamescmartinez** [comment]
@stevemdixon Don't commit the Sass cache files. Adding this to the `.gitignore` may help. https://github.com/github/gitignore/blob/master/Sass.gitignore

Once you remove those two files and add that .gitignore, you're golden. :+1:

**Comment by jamescmartinez** [comment]
@stevemdixon Also, `.saas-cache/*`

**Comment by stevemdixon** [comment]
@jamescmartinez Done!

**Comment by jamescmartinez** [comment]
@stevemdixon Hah! No, I meant remove that directory. You can also revert adding it to `.gitignore`. :)

**Comment by jamescmartinez** [comment]
:ship:

**Pull request merged**
